### ISSUE TITLE
Vector/fstream Demo

### ISSUE THREAD

**Issue by David-Sant** [csc233/Traffic-sim#5]
I have posted some of my code that I think will be very handy for reading in data for all our group. I have had a few issues using vectors though. I cannot "not" declare a size of my vector? Any thoughts?

Also can we put our files into folders on Github? This is going to get very messy if we cannot.

**Comment by csc233** [comment]
I moved all of your file into its own branch, that's about as close as it gets to folders on here as far as I have been able to find out.
