### ISSUE TITLE
Traction is misspelled as Tracktion in some places

### ISSUE THREAD

**Issue by spencemw** [csc233/Traffic-sim#7]
Traction is misspelled with a k included in the following functions....

**Vehicle.cpp 
Line135**
```
void Vehicle::setTracktion(int inputTraction)
 +{
 +	tracktion = inputTraction;
 +}
```

**Vehicle.h 
line 75:**  
`void setTracktion(int inputTraction); `

**Comment by csc233** [comment]
Fixed
